version: "3.9"  # optional since v1.27.0
services:
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/site/:ro
    links:
      - database
    depends_on:
      - database
  apache-secured:
    container_name: apache-secured
    build:
      context: ./apache-sec
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/site/:ro
    links:
      - database
    depends_on:
      - database
  reverse:
    image: owasp/modsecurity-crs:apache
    ports:
      - 8001:443
      - 8002:80
    environment:
      - ALLOWED_METHODS=GET HEAD POST PATCH DELETE OPTIONS
      - PROXY=1
      - BACKEND=http://voleibol-api-nestjs:3000
    networks:
      - volei-network

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=d086e517-a7f2-44a8-b0b0-a16f224bad5b
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=senhamuitoforte123
      - MYSQL_DATABASE=store
networks:
  volei-network:
    driver: bridge
